# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9953195a6aa5fd8aec7fb5be20c6a6e2a662c7d67aae8e16d5b3ac78c33b1069b1cbc7bf467d546a0bbada93e88a2b1e867c85cd4c5b9cf59682e009612d2b58

test:
  secret_key_base: 1f86cbabc33d76c9c60a97356a0ca7b6974420a07aeea9bff2f542fcd3dd4e00d58095e3d3a54db2cbbc712fbf65f9a0457bf57967df2ec6ff6b3dbb59207b11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
